os: linux
dist: xenial
language: python

jobs:
  fast_finish: true
  include:
    - python: 3.8  # This build will run only 'flake8'
      env: FLAKE_8=true
    - python: 3.7
    - python: 3.8
      env: BUILD_DOCS=true SUBMIT_CODECOV=true

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

before_install:
  - |
    if [ "${FLAKE_8}" == "true" ]; then
        pip install flake8
        flake8 .
        let res=$?
        echo "The project code was verified with 'flake8'. Exit code ($res)."
        exit $res
    fi

install:
  # The versions of pip and numpy that come pre-installed are often too old and
  # can cause problems. Upgrade them.
  - pip install --upgrade pip numpy
  # Install this package and the packages listed in requirements.txt.
  - pip install .
  # Install extra requirements for running tests and building docs.
  - pip install -r requirements-dev.txt

script:
  - coverage run -m pytest  # Run the tests and check for test coverage.
  - coverage report -m  # Generate test coverage report.
  - |
    set -e
    if [ "${BUILD_DOCS}" == "true" ]; then
        make -C docs/ html
        pip install doctr
        doctr deploy --built-docs docs/build/html .
    fi

after_success:
  - |
    if [ "${SUBMIT_CODECOV}" == "true" ]; then
        codecov  # Upload the report to codecov.
    fi
